### ISSUE TITLE
Lack of community resources

### ISSUE THREAD

**Issue by Morozzzko** [sobolevn/git-secret-rust#1]
I tried installing the application, but it's not working

I'd love to have a place to discuss the problems and get help, but there are no links. Are issues the appropriate place, or is there any slack/zullip/etc. group?

**Comment by theLastOfCats** [comment]
I suggest either Telegram or Discord.

@Morozzzko @sobolevn thoughts?

**Comment by Snawoot** [comment]
Hello,

I stumbled upon this issue as well. I was up to report this issue, but due to lack of Code of Conduct it was unclear how to do this properly without risk of improper interpersonal interactions. Is there some estimates about fix for that?

**Comment by stebunovd** [comment]
> I tried installing the application, but it's not working

well, it works on my machine, but I can't find how to run benchmarks. Help is appreciated.

**Comment by Snawoot** [comment]
@stebunovd 
I believe regular benchmarks are being run as part of CI workflow, so you can peek into configuration. One minor problem is: at this moment CI is down: ![Travis status shield](https://travis-ci.org/sobolevn/git-secret-rust.svg?branch=master)

I hope someone more experienced could fix that.

**Comment by sobolevn** [comment]
@Snawoot @stebunovd @theLastOfCats @Morozzzko that's funny! 

Thanks, guys 😄

**Comment by sobolevn** [comment]
P.S. Use github issues! It is a reliable communication channel. The only one proper project should have.
